### ISSUE TITLE
你使用GTQTCore的代码已经违反了GTQTcore代码的协议，请你尽快删除所有涉及内容

### ISSUE THREAD

**Issue by KeQingsocute520** [MisterNorwood/WFCore#5]
GTQTcore代码使用ARR协议，而你在未经我允许的情况下抄袭了我大量内容，现在我要求你尽快删除！
Your use of GTQTCore code has violated the protocol of GTQTCore code. Please delete all related content as soon as possible

The GTQTcore code uses the ARR protocol, and you copied a large amount of my content without my permission. Now I request that you delete it as soon as possible!

**Comment by last8kings** [comment]
ok

**Comment by last8kings** [comment]
can you update gt steam tech to 2.9 at least

**Comment by last8kings** [comment]
though I will also  say that copying other content and then proceeding to make your mod ARR is kind of a dick move.

**Comment by Leclowndu93150** [comment]
LMAO

**Comment by TheScienceDemon** [comment]
un fucking real lmfao
